### ISSUE TITLE
How and where to add the updated tutorials?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [DaveMDS/python-efl#1]
What's the best place to add the updated python-efl tutos? Where exactly in the docs? Thanks.

I'll then start grooming it.

**Comment by DaveMDS** [comment]
Hi, I will try to make a sort of empty skeleton in the docs today... or maybe tomorrow
I'm not touching the docs code since years, so I have to give a look

**Comment by DaveMDS** [comment]
I have done a bit of cleanup in the docs and some infra for the tutorials, look at the last commits.
I will make some more cleanups in the next days, but will not touch the docs/tutorials folder.. that is up to you now :)

Let me know if you need more help

PS: feel free to make improvements in every part of the docs, the texts really need some love

**Comment by DaveMDS** [comment]
2 years since then....
time to close this :(
