### ISSUE TITLE
Cython 3 incompatiblity leads to removal from some distros

### ISSUE THREAD

**Issue by rafspiny** [DaveMDS/python-efl#10]
From Gentoo last update:
```
!!! The following installed packages are masked:
- dev-python/python-efl-9999::enlightenment-live (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
# Michał Górny <mgorny@gentoo.org> (2024-03-10)
# Packages that still require <dev-python/cython-3 and do not promise
# a fix anytime soon.
#
# dev-python/python-efl: econnman as revdep, bug #925692.
# dev-python/pygame_sdl2: also py3.12, bug #911781
# games-engines/renpy: also py3.12, bug #925693
# sci-chemistry/mdtraj: also py3.12, PEP517, bug #911646.
#
# Includes their few reverse dependencies and their exclusive
# dependencies without Python 3.12 support.
#
# Removal on 2024-04-09.

Nothing to merge; quitting.```

What is the position towards cython 3?

**Comment by DaveMDS** [comment]
Hmm, porting python-efl to Cython3 is a HUGE work, 

I'm not going to do that work in a reasonable time

But:
why the package need Cython? distro packages should be generated from the released tarball, that do not need Cython to be built

Is there a reason why the package need cython?

**Comment by rafspiny** [comment]
Sorry for the silence. For an ebuild that tries to build from git, you need cython, don't you?

**Comment by rafspiny** [comment]
@DaveMDS To give more context, I get the source from git because I am maintaining an ebuild (in an overlay) for Gentoo. I could not find anymore the ebuild in the main portage tree too. I guess because of the dependency on Cython 0.29.x

See bug filed at https://bugs.gentoo.org/925692

**Comment by DaveMDS** [comment]
As I said the cython dependency should only be needed by developers who want to modify the code, distro packages should be build from official released tarball (that do not need Cython)

I'm not expert in gentoo ebuild, cant you build the gentoo package starting from the release tarball instead of git?

**Comment by rafspiny** [comment]
My bad. I am just using the release tarball now. Closing it. Thanks.
